bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 65535
timeout 0
tcp-keepalive 300
supervised no
databases 16
always-show-logo no
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 128mb
maxmemory-policy noeviction
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
activedefrag yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit pubsub 32mb 8mb 60
